/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package absensi.panel;


import absensi.component.filter.JTextFieldFilter;
import absensi.component.table.editor.TanggalEditor;
import absensi.component.table.renderer.TanggalRenderer;
import absensi.database.entity.Admin;
import absensi.database.entity.Siswa;
import absensi.database.entity.Wali;
import absensi.database.entity.service.SiswaService;
import absensi.database.entity.service.WaliService;
import absensi.database.entity.verfikasiinput.VerifikasiInput;
import absensi.database.utility.DatabaseUtilities;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chromatics
 */
public class EntrySiswa3 extends javax.swing.JPanel {    
    private SiswaService siswaService;
    private WaliService waliService;
    private VerifikasiInput verifikasiInput;
    
    private DefaultTableModel model;
    private Admin admin;
    
    
    /**
     * Creates new form EntrySiswa
     */
    public EntrySiswa3(Admin admin) {
        this.admin = admin;
        initComponents();
        siswaService = DatabaseUtilities.getSiswaService();
        waliService = DatabaseUtilities.getWali_Service();
        verifikasiInput = new VerifikasiInput();
        
        model = new DefaultTableModel();
        model.addColumn("NIS");//1
        model.addColumn("Nama Siswa");//2
        model.addColumn("Alamat");//3
        model.addColumn("Tempat Lahir");//4
        model.addColumn("Tanggal Lahir");//5
            
        model.addColumn("Jenis Kelamin");//6                                
        model.addColumn("Jurusan");//6                                
        model.addColumn("Kelas");//7                        
         
        model.addColumn("ID Wali");//11
        model.addColumn("Nama Wali");//12
        model.addColumn("Alamat Wali");//12
        model.addColumn("No Telpon Wali");//13
        tableSiswa.setModel(model);
        
        setInputFilter();
        setEditorRendereTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNIS1 = new javax.swing.JTextField();
        textNamaSiswa1 = new javax.swing.JTextField();
        textTempatLahir1 = new javax.swing.JTextField();
        tanggalLahir1 = new com.toedter.calendar.JDateChooser();
        comboJenisKelamin1 = new javax.swing.JComboBox();
        comboJurusan1 = new javax.swing.JComboBox();
        comboKelas1 = new javax.swing.JComboBox();
        textIdWali1 = new javax.swing.JTextField();
        textNamaWali1 = new javax.swing.JTextField();
        textNomerWali1 = new javax.swing.JTextField();
        textAlamatSiswa1 = new javax.swing.JTextField();
        textAlamatWali1 = new javax.swing.JTextField();
        panelBackground1 = new absensi.component.PanelBackground();
        panelTransparanRect1 = new absensi.component.PanelTransparanRect();
        jLabel4 = new javax.swing.JLabel();
        panelTransparanRect3 = new absensi.component.PanelTransparanRect();
        panelTransparanRect4 = new absensi.component.PanelTransparanRect();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonClear = new javax.swing.JButton();
        buttonClear1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        textTempatLahir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tanggalLahir = new com.toedter.calendar.JDateChooser();
        textNIS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        textNamaSiswa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        comboJenisKelamin = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboJurusan = new javax.swing.JComboBox();
        comboKelas = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        textAlamatSiswa = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        textNamaWali = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textNomerWali = new javax.swing.JTextField();
        textIdWali = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAlamatWali = new javax.swing.JTextArea();
        panelTransparanRect5 = new absensi.component.PanelTransparanRect();
        panelTransparanRect6 = new absensi.component.PanelTransparanRect();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labelJumlahBaris = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        textNIS1.setBorder(null);

        textNamaSiswa1.setBorder(null);

        textTempatLahir1.setBorder(null);

        comboJenisKelamin1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Jenis Kelamin-", "Laki - Laki", "Perempuan" }));
        comboJenisKelamin1.setBorder(null);
        comboJenisKelamin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJenisKelamin1ActionPerformed(evt);
            }
        });

        comboJurusan1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Jurusan-", "TKJ" }));
        comboJurusan1.setBorder(null);
        comboJurusan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJurusan1ActionPerformed(evt);
            }
        });

        comboKelas1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Kelas-", "X", "XI", "XII" }));
        comboKelas1.setBorder(null);
        comboKelas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKelas1ActionPerformed(evt);
            }
        });

        textIdWali1.setBorder(null);

        textNamaWali1.setBorder(null);

        textNomerWali1.setBorder(null);

        textAlamatSiswa1.setText("jTextField1");
        textAlamatSiswa1.setBorder(null);

        textAlamatWali1.setText("jTextField1");
        textAlamatWali1.setBorder(null);

        setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensi/panel/icon/administrator-icon.png"))); // NOI18N
        jLabel4.setText("Entry Siswa");

        javax.swing.GroupLayout panelTransparanRect1Layout = new javax.swing.GroupLayout(panelTransparanRect1);
        panelTransparanRect1.setLayout(panelTransparanRect1Layout);
        panelTransparanRect1Layout.setHorizontalGroup(
            panelTransparanRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTransparanRect1Layout.setVerticalGroup(
            panelTransparanRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparanRect1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setBackground(new java.awt.Color(102, 255, 102));
        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensi/panel/icon/write-document-icon.png"))); // NOI18N
        jLabel12.setText("Isi Form");

        javax.swing.GroupLayout panelTransparanRect4Layout = new javax.swing.GroupLayout(panelTransparanRect4);
        panelTransparanRect4.setLayout(panelTransparanRect4Layout);
        panelTransparanRect4Layout.setHorizontalGroup(
            panelTransparanRect4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTransparanRect4Layout.setVerticalGroup(
            panelTransparanRect4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12)
        );

        jPanel2.setOpaque(false);

        buttonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensi/panel/icon/broom-icon.png"))); // NOI18N
        buttonClear.setText("Bersihkan");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonClear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensi/panel/icon/user_blue_add.png"))); // NOI18N
        buttonClear1.setText("Tambah");
        buttonClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonClear1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonClear)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClear)
                    .addComponent(buttonClear1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Siswa"));
        jPanel3.setOpaque(false);

        jLabel7.setText(" | ");

        jLabel6.setText("NIS :");

        jLabel8.setText("Nama Siswa :");

        jLabel15.setText("Alamat Siswa :");

        jLabel16.setText("Jenis Kelamin :");

        comboJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Jenis Kelamin-", "Laki - Laki", "Perempuan" }));
        comboJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJenisKelaminActionPerformed(evt);
            }
        });

        jLabel17.setText("Tempat, Tanggal Lahir :");

        jLabel10.setText("Jurusan :");

        comboJurusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Jurusan-", "TKJ" }));
        comboJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJurusanActionPerformed(evt);
            }
        });

        comboKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Kelas-", "X", "XI", "XII" }));
        comboKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKelasActionPerformed(evt);
            }
        });

        jLabel9.setText("Kelas :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        textAlamatSiswa.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textNamaSiswa)
                    .addComponent(comboJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAlamatSiswa))
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(comboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(comboKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(textTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(comboJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(textAlamatSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Wali"));
        jPanel1.setOpaque(false);

        jLabel5.setText("ID Wali :");

        jLabel14.setText("Nomer Wali :");

        jLabel13.setText("Nama Wali :");

        jLabel19.setText("Alamat Wali :");

        textAlamatWali.setColumns(20);
        textAlamatWali.setRows(5);
        jScrollPane3.setViewportView(textAlamatWali);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNomerWali, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNamaWali, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textIdWali, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textIdWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textNamaWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(textNomerWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTransparanRect3Layout = new javax.swing.GroupLayout(panelTransparanRect3);
        panelTransparanRect3.setLayout(panelTransparanRect3Layout);
        panelTransparanRect3Layout.setHorizontalGroup(
            panelTransparanRect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparanRect4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTransparanRect3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTransparanRect3Layout.setVerticalGroup(
            panelTransparanRect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparanRect3Layout.createSequentialGroup()
                .addComponent(panelTransparanRect4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransparanRect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel18.setBackground(new java.awt.Color(102, 255, 102));
        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensi/panel/icon/write-document-icon.png"))); // NOI18N
        jLabel18.setText("Data Siswa");

        javax.swing.GroupLayout panelTransparanRect6Layout = new javax.swing.GroupLayout(panelTransparanRect6);
        panelTransparanRect6.setLayout(panelTransparanRect6Layout);
        panelTransparanRect6Layout.setHorizontalGroup(
            panelTransparanRect6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTransparanRect6Layout.setVerticalGroup(
            panelTransparanRect6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18)
        );

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableSiswa);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensi/panel/icon/application_view_detail.png"))); // NOI18N
        jButton3.setText("Lihat Detail");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensi/panel/icon/document_save.png"))); // NOI18N
        buttonTambah.setText("Simpan");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensi/panel/icon/remove.png"))); // NOI18N
        jButton2.setText("Hapus Baris");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensi/panel/icon/add.png"))); // NOI18N
        jButton1.setText("Tambah Baris");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelJumlahBaris.setText("jLabel2");

        jLabel1.setText("Jumlah Data :");

        javax.swing.GroupLayout panelTransparanRect5Layout = new javax.swing.GroupLayout(panelTransparanRect5);
        panelTransparanRect5.setLayout(panelTransparanRect5Layout);
        panelTransparanRect5Layout.setHorizontalGroup(
            panelTransparanRect5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparanRect6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTransparanRect5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparanRect5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelTransparanRect5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelJumlahBaris)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        panelTransparanRect5Layout.setVerticalGroup(
            panelTransparanRect5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparanRect5Layout.createSequentialGroup()
                .addComponent(panelTransparanRect6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransparanRect5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTambah)
                    .addGroup(panelTransparanRect5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(labelJumlahBaris))
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBackground1Layout = new javax.swing.GroupLayout(panelBackground1);
        panelBackground1.setLayout(panelBackground1Layout);
        panelBackground1Layout.setHorizontalGroup(
            panelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparanRect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparanRect3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparanRect5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBackground1Layout.setVerticalGroup(
            panelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackground1Layout.createSequentialGroup()
                .addComponent(panelTransparanRect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTransparanRect3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTransparanRect5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelBackground1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        int j=0;
        try {
            for (int i = 0; i < model.getRowCount(); i++) {
                Wali wali = new Wali();
                wali.setIdWali(tableSiswa.getValueAt(i, 8).toString());
                wali.setAdmin(admin);
                wali.setNamaWali(tableSiswa.getValueAt(i, 9).toString());
                wali.setAlamatWali(tableSiswa.getValueAt(i, 10).toString());                
                wali.setNopeWali(tableSiswa.getValueAt(i, 11).toString());

                Siswa siswa = new Siswa();
                siswa.setNis(tableSiswa.getValueAt(i, 0).toString());
                siswa.setWali(wali);
                siswa.setAdmin(admin);
                siswa.setNamaSiswa(tableSiswa.getValueAt(i, 1).toString());                
                siswa.setAlamatSiswa(tableSiswa.getValueAt(i, 2).toString());
                siswa.setTempatLahirSiswa(tableSiswa.getValueAt(i, 3).toString());
                
                SimpleDateFormat formatter = new SimpleDateFormat("dd MMMM yyyy");
                Object object = tableSiswa.getValueAt(i, 4);                   
                Date date = (Date) object;                                                    
                
                siswa.setTglLahirSiswa(date);                
                siswa.setJkSiswa(tableSiswa.getValueAt(i, 5).toString());
                siswa.setJurusanSiswa(tableSiswa.getValueAt(i, 6).toString());
                siswa.setKelasSiswa(tableSiswa.getValueAt(i, 7).toString());                
                
                if (verifikasiInput.verifikasiWali(wali) & verifikasiInput.verifikasiSiswa(siswa)) {
                    if (waliService.insertWali(wali)==true) {
                        if(siswaService.insertSiswa(siswa)==true){
                            j++;
                        }
                    }
                }
            }
            
            if (j == tableSiswa.getRowCount()) {
                JOptionPane.showMessageDialog(null, "Data sudah di masukkan");                
                hapusTable();
            }else{
                JOptionPane.showMessageDialog(null, "Maaf, sebagian data tidak bisa di masukkan");
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Maaf, data ada yang kosong, karena : "+e.getMessage());
            e.printStackTrace();
        }                  
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClear1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        jDialog1.setSize(966, 707);
//        jDialog1.setTitle("Detail Siswa");
//        jDialog1.setLocationRelativeTo(null);
//        jDialog1.setVisible(true);                
        DialogDetailSiswa detailSiswa1 = new DialogDetailSiswa(null, true, admin);
        detailSiswa1.setLocationRelativeTo(null);
        detailSiswa1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJenisKelaminActionPerformed

    private void comboJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJurusanActionPerformed

    private void comboKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboKelasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (model.getRowCount()<=0) {
            JOptionPane.showMessageDialog(null, "Maaf, tabel masih kosong");
        }else{
            model.removeRow(model.getRowCount()-1);
        }

        labelJumlahBaris.setText(tableSiswa.getRowCount()+"");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        model.addRow(new Object[tableSiswa.getColumnCount()]);
        labelJumlahBaris.setText(tableSiswa.getRowCount()+"");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboJenisKelamin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJenisKelamin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJenisKelamin1ActionPerformed

    private void comboJurusan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJurusan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJurusan1ActionPerformed

    private void comboKelas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKelas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboKelas1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonClear1;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JComboBox comboJenisKelamin;
    private javax.swing.JComboBox comboJenisKelamin1;
    private javax.swing.JComboBox comboJurusan;
    private javax.swing.JComboBox comboJurusan1;
    private javax.swing.JComboBox comboKelas;
    private javax.swing.JComboBox comboKelas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelJumlahBaris;
    private absensi.component.PanelBackground panelBackground1;
    private absensi.component.PanelTransparanRect panelTransparanRect1;
    private absensi.component.PanelTransparanRect panelTransparanRect3;
    private absensi.component.PanelTransparanRect panelTransparanRect4;
    private absensi.component.PanelTransparanRect panelTransparanRect5;
    private absensi.component.PanelTransparanRect panelTransparanRect6;
    private javax.swing.JTable tableSiswa;
    private com.toedter.calendar.JDateChooser tanggalLahir;
    private com.toedter.calendar.JDateChooser tanggalLahir1;
    private javax.swing.JScrollPane textAlamatSiswa;
    private javax.swing.JTextField textAlamatSiswa1;
    private javax.swing.JTextArea textAlamatWali;
    private javax.swing.JTextField textAlamatWali1;
    private javax.swing.JTextField textIdWali;
    private javax.swing.JTextField textIdWali1;
    private javax.swing.JTextField textNIS;
    private javax.swing.JTextField textNIS1;
    private javax.swing.JTextField textNamaSiswa;
    private javax.swing.JTextField textNamaSiswa1;
    private javax.swing.JTextField textNamaWali;
    private javax.swing.JTextField textNamaWali1;
    private javax.swing.JTextField textNomerWali;
    private javax.swing.JTextField textNomerWali1;
    private javax.swing.JTextField textTempatLahir;
    private javax.swing.JTextField textTempatLahir1;
    // End of variables declaration//GEN-END:variables

    void hapusTable(){
       for( int i = model.getRowCount() - 1; i >= 0; i-- ){
             model.removeRow(i);
        }
    }
    
    
    void setEditorRendereTable(){
        //nis
        tableSiswa.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(textNIS1));
        
        //nama siswa
        tableSiswa.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(textNamaSiswa1));
        
        //alamat
        tableSiswa.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(textAlamatSiswa1));
        
         //tempat lahir
        tableSiswa.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(textTempatLahir1));
        
        //tanggal lahir
        tableSiswa.getColumnModel().getColumn(4).setCellRenderer(new TanggalRenderer());        
        tableSiswa.getColumnModel().getColumn(4).setCellEditor(new TanggalEditor(tanggalLahir1));
        
        //jenis kelamin
        tableSiswa.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(comboJenisKelamin1));
                       
        //jurusan
        tableSiswa.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(comboJurusan1));
        
        //kelas
        tableSiswa.getColumnModel().getColumn(7).setCellEditor(new DefaultCellEditor(comboKelas1));
                        
        //id wali
        tableSiswa.getColumnModel().getColumn(8).setCellEditor(new DefaultCellEditor(textIdWali1));        
        
        //nama wali
        tableSiswa.getColumnModel().getColumn(9).setCellEditor(new DefaultCellEditor(textNamaWali1));
        
        //alamat wali
        tableSiswa.getColumnModel().getColumn(10).setCellEditor(new DefaultCellEditor(textAlamatWali1));
        
        //no pe
        tableSiswa.getColumnModel().getColumn(11).setCellEditor(new DefaultCellEditor(textNomerWali1));
    }
    
    void setInputFilter(){
        //Filter untuk input form
        textNIS.setDocument(new JTextFieldFilter(JTextFieldFilter.NUMERIC, 6));
        textNamaSiswa.setDocument(new JTextFieldFilter(JTextFieldFilter.ALPHABETIC, 50));
        textNamaWali.setDocument(new JTextFieldFilter(JTextFieldFilter.ALPHABETIC, 50));
        textNomerWali.setDocument(new JTextFieldFilter(JTextFieldFilter.NUMERIC, 13));
        textTempatLahir.setDocument(new JTextFieldFilter(JTextFieldFilter.ALPHABETIC, 30));
        textIdWali.setDocument(new JTextFieldFilter(JTextFieldFilter.NUMERIC, 6));
        
        //Filter untuk input table
        textNIS1.setDocument(new JTextFieldFilter(JTextFieldFilter.NUMERIC, 6));
        textNamaSiswa1.setDocument(new JTextFieldFilter(JTextFieldFilter.ALPHABETIC, 50));
        textNamaWali1.setDocument(new JTextFieldFilter(JTextFieldFilter.ALPHABETIC, 50));
        textNomerWali1.setDocument(new JTextFieldFilter(JTextFieldFilter.NUMERIC, 13));
        textTempatLahir1.setDocument(new JTextFieldFilter(JTextFieldFilter.ALPHABETIC, 30));
        textAlamatSiswa1.setDocument(new JTextFieldFilter(JTextFieldFilter.ADDRESS, 100));        
        textAlamatWali.setDocument(new JTextFieldFilter(JTextFieldFilter.ADDRESS, 100));        
        textIdWali1.setDocument(new JTextFieldFilter(JTextFieldFilter.NUMERIC, 6));
    }    
}
