/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package absensi.main;

import absensi.database.entity.Admin;
import absensi.panel.About;
import absensi.panel.BackUp;
import absensi.panel.DaftarKehadiran;
import absensi.panel.LaporanAbsensi;
import absensi.panel.ManajemenSiswa;
import absensi.panel.Welcome;
import absensi.panel.coba.Admin1;
import absensi.panel.coba.Siswa1;
import absensi.panel.coba.Absensi1;
import absensi.panel.AbsenHarian;
import absensi.panel.DetailAbsen;
import absensi.panel.coba.Siswa2;
import com.stripbandunk.jglasspane.component.DialogBackgroundColor;
import com.stripbandunk.jglasspane.transition.FadeTransition;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.CardLayout;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Chromatics
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form AMin
     */
    private Admin admin;
    public Main(Admin admin) {
        try {
            UIManager.setLookAndFeel(new WindowsLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.admin=admin;     
        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        setGlassPane(jGlassPane1);
        getGlassPane().setVisible(true);        
        jGlassPane1.addGlassPaneComponent(transitionComponent1);
        jGlassPane1.addGlassPaneComponent(dialogComponent1);
        dialogComponent1.setDialogBackground(new DialogBackgroundColor(new Color(getBackground().getRed(), getBackground().getGreen(), getBackground().getBlue()), 
                0.5f));              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGlassPane1 = new com.stripbandunk.jglasspane.JGlassPane();
        transitionComponent1 = new com.stripbandunk.jglasspane.component.TransitionComponent();
        dialogComponent1 = new com.stripbandunk.jglasspane.component.DialogComponent();
        login21 = new absensi.panel.coba.Login2();
        jPanel1 = new absensi.component.PanelBackground();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuWelcome = new javax.swing.JMenuItem();
        menuTutupAplikasi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuEntrySiswa = new javax.swing.JMenuItem();
        menuAdmin = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuSms = new javax.swing.JMenuItem();
        menuAbsensi = new javax.swing.JMenuItem();
        menuAbsensi1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuLaporanAbsensi = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuAbout1 = new javax.swing.JMenuItem();
        menuAbout2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());
        Welcome welcome = new Welcome(admin);
        absensi.panel.EntryAdmin1 entryAdmin = new absensi.panel.EntryAdmin1();
        //EntrySiswa entrySiswa = new EntrySiswa();
        LaporanAbsensi laporanAbsensi = new LaporanAbsensi();
        absensi.panel.coba.PanelAbsensi absensi = new absensi.panel.coba.PanelAbsensi(admin);
        DaftarKehadiran daftarKehadiran = new DaftarKehadiran();
        About about = new About();
        ManajemenSiswa manajemenSiswa = new ManajemenSiswa();
        BackUp backUp = new BackUp();

        Admin1 panelAdmin = new absensi.panel.coba.Admin1();
        Siswa1 panelSiswa1 = new absensi.panel.coba.Siswa1(admin);
        Absensi1 panelAbsensi = new absensi.panel.coba.Absensi1(admin);
        AbsenHarian panelAbsensi2 = new AbsenHarian(admin);
        Siswa2 panelSiswa2 = new Siswa2(admin);
        absensi.panel.EntrySiswa3 panelSiswa3 = new absensi.panel.EntrySiswa3(admin);
        DetailAbsen detailAbsen = new DetailAbsen(admin);

        jPanel1.add(welcome, "welcome");
        jPanel1.add(entryAdmin, "admin");
        jPanel1.add(absensi, "absensi");
        jPanel1.add(laporanAbsensi, "laporanAbsensi");

        jPanel1.add(panelAdmin, "admin1");
        jPanel1.add(panelSiswa1, "siswa1");
        jPanel1.add(panelSiswa2, "siswa2");
        jPanel1.add(panelAbsensi, "absensi1");
        jPanel1.add(panelAbsensi2, "absensi2");
        jPanel1.add(daftarKehadiran, "daftarKehadiran");
        jPanel1.add(about, "about");
        jPanel1.add(manajemenSiswa, "manajemenSiswa");
        jPanel1.add(backUp, "backUp");
        jPanel1.add(panelSiswa3, "siswa3");
        jPanel1.add(detailAbsen, "detailAbsen");
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        menuWelcome.setText("Selamat Datang");
        menuWelcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWelcomeActionPerformed(evt);
            }
        });
        jMenu1.add(menuWelcome);

        menuTutupAplikasi.setText("Tutup Aplikasi");
        jMenu1.add(menuTutupAplikasi);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Entry Data");

        menuEntrySiswa.setText("Siswa");
        menuEntrySiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntrySiswaActionPerformed(evt);
            }
        });
        jMenu2.add(menuEntrySiswa);

        menuAdmin.setText("Admin");
        menuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminActionPerformed(evt);
            }
        });
        jMenu2.add(menuAdmin);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Layanan");

        menuSms.setText("Absen Harian");
        menuSms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSmsActionPerformed(evt);
            }
        });
        jMenu3.add(menuSms);

        menuAbsensi.setText("Daftar Kehadiran");
        menuAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbsensiActionPerformed(evt);
            }
        });
        jMenu3.add(menuAbsensi);

        menuAbsensi1.setText("Detail Absen");
        menuAbsensi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbsensi1ActionPerformed(evt);
            }
        });
        jMenu3.add(menuAbsensi1);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Laporan");

        menuLaporanAbsensi.setText("Laporan Absensi");
        menuLaporanAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanAbsensiActionPerformed(evt);
            }
        });
        jMenu5.add(menuLaporanAbsensi);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Manajemen");

        menuAbout1.setText("Siswa");
        menuAbout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbout1ActionPerformed(evt);
            }
        });
        jMenu6.add(menuAbout1);

        menuAbout2.setText("Data");
        menuAbout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbout2ActionPerformed(evt);
            }
        });
        jMenu6.add(menuAbout2);

        jMenuBar1.add(jMenu6);

        jMenu4.setText("Help");

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu4.add(menuAbout);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuWelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWelcomeActionPerformed
        // TODO add your handling code here:
        FadeTransition transition = new FadeTransition();
        transition.setClip(jGlassPane1.getClip(jPanel1));        
        transition.setPaint(jPanel1.getBackground());
        
        transitionComponent1.setTransition(transition);
        transitionComponent1.start(1500);
                        
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "welcome");
    }//GEN-LAST:event_menuWelcomeActionPerformed

    private void menuEntrySiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntrySiswaActionPerformed
        // TODO add your handling code here:
        FadeTransition transition = new FadeTransition();
        transition.setClip(jGlassPane1.getClip(jPanel1));        
        transition.setPaint(jPanel1.getBackground());
        
        transitionComponent1.setTransition(transition);
        transitionComponent1.start(1500);        
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "siswa3");
    }//GEN-LAST:event_menuEntrySiswaActionPerformed

    private void menuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminActionPerformed
        // TODO add your handling code here:
        FadeTransition transition = new FadeTransition();
        transition.setClip(jGlassPane1.getClip(jPanel1));        
        transition.setPaint(jPanel1.getBackground());
        
        transitionComponent1.setTransition(transition);
        transitionComponent1.start(1500);        
        
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "admin");
    }//GEN-LAST:event_menuAdminActionPerformed

    private void menuAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbsensiActionPerformed
        // TODO add your handling code here:
        FadeTransition transition = new FadeTransition();
        transition.setClip(jGlassPane1.getClip(jPanel1));        
        transition.setPaint(jPanel1.getBackground());
        
        transitionComponent1.setTransition(transition);
        transitionComponent1.start(1500);        
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "daftarKehadiran");
    }//GEN-LAST:event_menuAbsensiActionPerformed

    private void menuLaporanAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanAbsensiActionPerformed
        // TODO add your handling code here:
        FadeTransition transition = new FadeTransition();
        transition.setClip(jGlassPane1.getClip(jPanel1));        
        transition.setPaint(jPanel1.getBackground());
        
        transitionComponent1.setTransition(transition);
        transitionComponent1.start(1500);
        
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "laporanAbsensi");
    }//GEN-LAST:event_menuLaporanAbsensiActionPerformed

    private void menuSmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSmsActionPerformed
        // TODO add your handling code here:
        FadeTransition transition = new FadeTransition();
        transition.setClip(jGlassPane1.getClip(jPanel1));        
        transition.setPaint(jPanel1.getBackground());
        
        transitionComponent1.setTransition(transition);
        transitionComponent1.start(1500);
        
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "absensi2");
        
    }//GEN-LAST:event_menuSmsActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        FadeTransition transition = new FadeTransition();
        transition.setClip(jGlassPane1.getClip(jPanel1));        
        transition.setPaint(jPanel1.getBackground());
        
        transitionComponent1.setTransition(transition);
        transitionComponent1.start(1500);
        
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "about");
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuAbout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbout1ActionPerformed
        FadeTransition transition = new FadeTransition();
        transition.setClip(jGlassPane1.getClip(jPanel1));        
        transition.setPaint(jPanel1.getBackground());
        
        transitionComponent1.setTransition(transition);
        transitionComponent1.start(1500);
        
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "manajemenSiswa");
    }//GEN-LAST:event_menuAbout1ActionPerformed

    private void menuAbout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbout2ActionPerformed
        // TODO add your handling code here:
        FadeTransition transition = new FadeTransition();
        transition.setClip(jGlassPane1.getClip(jPanel1));        
        transition.setPaint(jPanel1.getBackground());
        
        transitionComponent1.setTransition(transition);
        transitionComponent1.start(1500);
        
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "backUp");
    }//GEN-LAST:event_menuAbout2ActionPerformed

    private void menuAbsensi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbsensi1ActionPerformed
        // TODO add your handling code here:
                FadeTransition transition = new FadeTransition();
        transition.setClip(jGlassPane1.getClip(jPanel1));        
        transition.setPaint(jPanel1.getBackground());
        
        transitionComponent1.setTransition(transition);
        transitionComponent1.start(1500);
        
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "detailAbsen");
    }//GEN-LAST:event_menuAbsensi1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Admin admin=null;
//                
//                new Main(admin).setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.stripbandunk.jglasspane.component.DialogComponent dialogComponent1;
    private com.stripbandunk.jglasspane.JGlassPane jGlassPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private absensi.component.PanelBackground jPanel1;
    private absensi.panel.coba.Login2 login21;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuAbout1;
    private javax.swing.JMenuItem menuAbout2;
    private javax.swing.JMenuItem menuAbsensi;
    private javax.swing.JMenuItem menuAbsensi1;
    private javax.swing.JMenuItem menuAdmin;
    private javax.swing.JMenuItem menuEntrySiswa;
    private javax.swing.JMenuItem menuLaporanAbsensi;
    private javax.swing.JMenuItem menuSms;
    private javax.swing.JMenuItem menuTutupAplikasi;
    private javax.swing.JMenuItem menuWelcome;
    private com.stripbandunk.jglasspane.component.TransitionComponent transitionComponent1;
    // End of variables declaration//GEN-END:variables
}
